#!/bin/sh
#/etc/init.d/imx-watchdog: start imx-watchdog daemon.

### BEGIN INIT INFO
# Provides:          imx-watchdog
# Short-Description: Start hardware imx-watchdog daemon
# X-Start-Before:    checkroot
# Should-Stop:       
# Default-Start:     S
### END INIT INFO


LOG_FILE=/var/log/imx-watchdog.log
PATH=/usr/bin:/etc/init.d
. /lib/lsb/init-functions

case "$1" in
  start)
	printf "%-50s" " * Starting imx-watchdog..."
	printf "\t\t\t%s\n" " [ OK ]"
	devregs 0x20bc000 0x2034
	echo "imx-watchdog started with 10second timeout" >> $LOG_FILE
	;;
   status)
	red='\033[0;31m'
	white='\33[0;37m'
	wdt_register=`devregs 0x20bc000 | tail -c 3`
	if [ $wdt_register="35" ] || [ $wdt_register="34" ]
	then
		echo " * imx-watchdog is enabled"
	else
		echo " ${red}*${white} imx-watchdog disabled"
	fi
	 
 	
	
    	;;
  *)
	echo "Usage: /etc/init.d/imx-pinger {start|status}"
	exit 1
	;;
esac

exit 0
